### ISSUE TITLE
Getting issue when uploading app on tetsflight using Hover

### ISSUE THREAD

**Issue by tapendrasinghal** [pedrommcarrasco/Hover#10]
Hey,

When we are updating app by using Hover we are getting error through App store.
This is the error
ERROR ITMS-90085: "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable."

When removing hover it is working fine 
Can you please let us know if any setting have to done for this.

we used pod Hover to install hover in project.
But not uploading app on testflight using this.

**Comment by pedrommcarrasco** [comment]
Hi @tapendrasinghal,

I'm sorry about it and I'll try to guide/help you through it.
Could you please provide more details such as Hover version, you projects deployment target and Xcode version?
