### ISSUE TITLE
Allow animation when opening the options

### ISSUE THREAD

**Issue by bguidolim** [pedrommcarrasco/Hover#16]
Hey @pedrommcarrasco

First of all, thanks for the great library :)

I've added a way to animate the HoverButton when opening, and I would like to contribute to the library, however, I'm not finding the best way to make it in a generic way, so other devs can use this too.

Here is the result I wanted to achieve:
![Screen Recording 2021-07-02 at 12 33 27](https://user-images.githubusercontent.com/987360/124262383-448ef780-db32-11eb-961e-42469e9b3d79.gif)

Currently, I've added a constant (following the pattern you've set already), but for sure this is not the best approach for the general public.

Could you please take a look and guide me if you think it's a good idea to add to the library?

Here you can find the current implementation: https://github.com/pedrommcarrasco/Hover/compare/master...bguidolim:rotate-animation

Thank you :)

**Comment by pedrommcarrasco** [comment]
> I've added a way to animate the HoverButton when opening, and I would like to contribute to the library, however, I'm not finding the best way to make it in a generic way, so other devs can use this too.

This will always be an issue and I think our best option where could be an enum similar to this 👇  where `none` would be the default value on `HoverConfiguration`'s `init`.
```
enum ImageExpandAnimation {
    case none
    case rotation
   // case rotationAndTransform(UIImage) e.g.: We could add an option in the future to rotate while changing the image to something different
}
```

Other than that, your implementation would be more or less what we could do. I'd just move the animation itself from `isExpanded`'s `didSet` to `animate(isOpening:, anchor:, completion:)` - and of course, we would need to update that code to switch over the `ImageExpandAnimation` and determine which animation it should use.

What do you think?

**Comment by bguidolim** [comment]
@pedrommcarrasco I've created a PR considering the ideas you've posted here.
