### ISSUE TITLE
Dependency "Hover" has no shared framework schemes

### ISSUE THREAD

**Issue by burgercode** [pedrommcarrasco/Hover#3]
Using Carthage with `carthage update`:

```
*** Skipped building Hover due to the error:
Dependency "Hover" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/pedrommcarrasco/Hover/issues/new
```

Xcode 10.3, Carthage 0.33.0 and macOS 10.14.5

By the way excellent project :)

**Comment by pedrommcarrasco** [comment]
Oh 🤦‍♂ 
Thank you for letting me know @burgercode, would you like to fix it and therefore become a contributor?

Thanks for the kind words!

**Comment by burgercode** [comment]
I'm sorry, but I really don't have time now :/ But I would be happy to contribute in the future! Thank you!
