### ISSUE TITLE
How to disable drag functionality? i Want to fix it's possition

### ISSUE THREAD

**Issue by AbdulRahman-Khursheed** [pedrommcarrasco/Hover#8]

**Comment by AbdulRahman-Khursheed** [comment]
It's possible to fix the button? I fix it on top left corner. But it's also drag and then come back on the top left. I also want to remove this drag functionality. How it's possible?

**Comment by pedrommcarrasco** [comment]
Such feature is not yet supported.
You can add so by opening a PR where you add a property to HoverConfiguration or if you want a quick dirty hack to fit your use case by going through hoverView.subviews and disabling the Pan gesture
